### ISSUE TITLE
Pull-Requests no longer working on BitBucket Server 7.0

### ISSUE THREAD

**Issue by viceice** [jenkinsci/bitbucket-branch-source-plugin#287]
### Your checklist for this issue

- [x] Jenkins version: 2.204.5

- [x] Plugin version: 2.7.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: 7.0.0, 7.0.1

### Description

This plugin is no longer able to fetch and build pull-requests. Looks like thay changed the api without writing a note.

```
06:01:26  Started by user XXX YYY
06:01:26  Running as XXX YYY
06:01:34  ERROR: Could not do lightweight checkout, falling back to heavyweight
06:01:34  java.io.FileNotFoundException: URL: /rest/api/1.0/projects/proj/repos/repo/browse/Jenkinsfile?at=pull-requests%2F580%2Fmerge&start=0&limit=500
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:831)
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1123)
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
06:01:34  	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
06:01:34  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
06:01:34  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
06:01:34  	at hudson.model.ResourceController.execute(ResourceController.java:97)
06:01:34  	at hudson.model.Executor.run(Executor.java:427)
06:01:34  Checking out git https://xxx.yyyy.de/scm/proj/repo.git https://xxx.yyyy.de/scm/proj/repo.git into /var/jenkins_home/workspace/proj_repo_PR-580@script to read Jenkinsfile
06:01:34  using credential a63b7cb8-6690-4c0b-81b8-93969a0fabac
06:01:35  using credential a63b7cb8-6690-4c0b-81b8-93969a0fabac
06:01:35   > git rev-parse --is-inside-work-tree # timeout=10
06:01:35  Fetching changes from 2 remote Git repositories
06:01:35   > git config remote.origin.url https://xxx.yyyy.de/scm/proj/repo.git # timeout=10
06:01:35  Cleaning workspace
06:01:35   > git rev-parse --verify HEAD # timeout=10
06:01:35  No valid HEAD. Skipping the resetting
06:01:35   > git clean -ffdx # timeout=10
06:01:35  Pruning obsolete local branches
06:01:35  Fetching upstream changes from https://xxx.yyyy.de/scm/proj/repo.git
06:01:35   > git --version # timeout=10
06:01:35  using GIT_ASKPASS to set credentials 
06:01:35   > git fetch --tags --force --progress --prune -- https://xxx.yyyy.de/scm/proj/repo.git +refs/pull-requests/580/from:refs/remotes/origin/PR-580 # timeout=10
06:01:35  ERROR: Error fetching remote repo 'origin'
06:01:35  hudson.plugins.git.GitException: Failed to fetch from https://xxx.yyyy.de/scm/proj/repo.git
06:01:35  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
06:01:35  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
06:01:35  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
06:01:35  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
06:01:35  	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
06:01:35  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
06:01:35  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
06:01:35  	at hudson.model.ResourceController.execute(ResourceController.java:97)
06:01:35  	at hudson.model.Executor.run(Executor.java:427)
06:01:35  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --prune -- https://xxx.yyyy.de/scm/proj/repo.git +refs/pull-requests/580/from:refs/remotes/origin/PR-580" returned status code 128:
06:01:35  stdout: 
06:01:35  stderr: fatal: Couldn't find remote ref refs/pull-requests/580/from
06:01:35  
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
06:01:35  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:907)
06:01:35  	... 8 more
06:01:35  ERROR: Error fetching remote repo 'origin'
06:01:35  [Bitbucket] Notifying pull request build result
06:01:36  [Bitbucket] Build result notified
06:01:36  ERROR: Maximum checkout retry attempts reached, aborting
06:01:36  Finished: FAILURE
```

https://community.atlassian.com/t5/Bitbucket-questions/Bitbucket-Server-7-0-PR-fetch-from-not-working/qaq-p/1320053

**Comment by Jetersen** [comment]
🤷‍♂ Feel free to revert until some kind soul contributes the code for Bitbucket 7

**Comment by viceice** [comment]
Ok, trying to build a fix.

**Comment by Jetersen** [comment]
Not seeing anything note worthy: https://developer.atlassian.com/server/bitbucket/reference/api-changelog/ so edouble 🤷‍♂

**Comment by viceice** [comment]
as a workaround i disable pr's and only build regular branches

**Comment by Jetersen** [comment]
Hmm sure your not a one time thing: https://docs.atlassian.com/bitbucket-server/rest/7.0.1/bitbucket-rest.html#idp280 this is still documented as is.

**Comment by viceice** [comment]
ok, updating to 7.01 to see if its a bitbucket bug

**Comment by Jetersen** [comment]
So is this: https://docs.atlassian.com/bitbucket-server/rest/7.0.1/bitbucket-rest.html#idp206

**Comment by Jetersen** [comment]
The `at` field looks funky though 😓

**Comment by viceice** [comment]
yes, i think there should be the commit id.

**Comment by Jetersen** [comment]
You'd have to debug what the API is returning since that is somewhat unexpected 🤔

**Comment by viceice** [comment]
ok, np. i have some java experience. i also know the bitbucket api from out [renovatebot](https://github.com/renovatebot/renovate) 😅

**Comment by viceice** [comment]
Looks like 7.0.1 is working 🤔

**Comment by Jetersen** [comment]
😖

**Comment by viceice** [comment]
so closing this as ist working again. :man_shrugging:

**Comment by viceice** [comment]
There is something wrong. 

`git fetch +refs/pull-requests/575/from:refs/remotes/origin/PR-575`

![image](https://user-images.githubusercontent.com/1798109/76192065-2a186880-61e1-11ea-87f0-ead3634ddccd.png)

They should be equal. pr is opened from `renovate/jint-3.0.x` to `master`

**Comment by wwuck** [comment]
I'm also seeing this same issue with building PRs after upgrading to Bitbucket 7.0.1 yesterday.  Anything I can do/test to help get this fixed?

**Comment by viceice** [comment]
Nope, disabled pr build for now. Currently the only fix is to downgrade.

**Comment by viceice** [comment]
`stderr: fatal: Couldn't find remote ref refs/pull-requests/580/from` is gone with 7.0.1, but `refs/pull-requests/580/from` is no longer updated by bitbucket after pushing new commits.

**Comment by jftsunami** [comment]
@viceice Just so you know, the pull request refs have never been supported by BitBucket / Atlassian as part of their API. https://community.atlassian.com/t5/Bitbucket-questions/Difference-of-refs-pull-requests-lt-ID-gt-merge-and-refs-pull/qaq-p/772142  This plugin needs to go via the Rest API to get the correct needed data.

**Comment by viceice** [comment]
OK, trying to send a pr which uses the rest api

**Comment by viceice** [comment]
Are I'm right that this need to be fixed here:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/3dbf6b60550d90ab6e98991f51740c4bc279ffb4/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java#L101-L110

**Comment by alexey-pelykh** [comment]
Have we considered forcing the refs creation again by different call to API? Bad approach, but a quick-fix? (as discussed in https://issues.jenkins-ci.org/browse/JENKINS-61493)

**Comment by dcherniv** [comment]
I tried the latest RC 
https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc629.f242e60a14b4/
Doesn't appear to work properly. We have git-lfs on one of our repos and heavyweight checkout appears to be broken with git lfs.
git lfs binary is installed on the jenkins master. 
```
12:54:24  ERROR: Could not do lightweight checkout, falling back to heavyweight
12:54:24  java.io.FileNotFoundException: URL: /rest/api/1.0/projects/ML/repos/repo/browse/Jenkinsfile?at=pull-requests%2F219%2Fmerge&start=0&limit=500
12:54:24  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:831)
12:54:24  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1123)
12:54:24  	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
12:54:24  	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
12:54:24  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
12:54:24  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
12:54:24  	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:54:24  	at hudson.model.Executor.run(Executor.java:428)
12:54:24  Checking out git https://bb.example.com/scm/ML/repo.git https://bb.example.com/scm/ML/repo.git into /var/jenkins_home/workspace/repo_PR-219@script to read Jenkinsfile
12:54:24  using credential jenkins
12:54:24  using credential jenkins
```
Which then later times out with:
```
12:54:40  Merging remotes/upstream/master commit a9bc1aac607fa24a97711736a18bfda3c651d1f1 into PR head commit 75dc89073f8627ecd7434f614138e726016d00a0
12:54:40   > git config core.sparsecheckout # timeout=10
12:54:40   > git checkout -f 75dc89073f8627ecd7434f614138e726016d00a0 # timeout=10
12:59:08  ERROR: Checkout failed
12:59:08  java.lang.InterruptedException
12:59:08  	at java.lang.Object.wait(Native Method)
12:59:08  	at java.lang.Object.wait(Object.java:502)
12:59:08  	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
12:59:08  	at hudson.Proc$LocalProc.join(Proc.java:327)
12:59:08  	at hudson.Proc.joinWithTimeout(Proc.java:172)
12:59:08  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2423)
12:59:08  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:81)
12:59:08  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2743)
12:59:08  	at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:144)
12:59:08  	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:110)
12:59:08  	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1063)
12:59:08  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1168)
12:59:08  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
12:59:08  	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
12:59:08  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
12:59:08  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
12:59:08  	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:59:08  	at hudson.model.Executor.run(Executor.java:428)
12:59:08  [Bitbucket] Notifying pull request build result
12:59:08  [Bitbucket] Build result notified
12:59:08  ERROR: Maximum checkout retry attempts reached, aborting
12:59:08  Finished: FAILURE
```

**Comment by spacehorst** [comment]
I can confirm this issue using Plugin Version 2.7.0 with Bitbucket Server 7.1.0

**Comment by mlasevich** [comment]
+1 on issue with BB 7.1.0 - our guys upgraded BB this weekend and all PRs no longer build (and we lean heavily on them) - is there a patch yet?

**Comment by jetersen** [comment]
Both #294 and #302 is a workable solution.

Although #302 needs some refinements as it is basically a hack abusing the can merge api call. While it would be great to support both can merge and poking the PR changes api.

**Comment by mlasevich** [comment]
I back-ported #294 to a fork of 2.5.0 (I named it 2.5.1) because due to our setup we cannot upgrade to 2.6.0+ yet. So the question is - is there a process in Jenkins ecosystem to release backported versions for those who are stuck, like us? Obviously we can always build local versions, but would be nice to have official release somewhere...

**Comment by jetersen** [comment]
My first question would be why are you stuck?

**Comment by mlasevich** [comment]
Not sure it qualifies as 'good' reason, but we are CloudBees Enterprise customers, and their managed masters have a very specific plugin version set, usually 3-4 mos behind the times. For past few releases they have been fixed at 2.5.0 :-(. Often it will not be a big deal to update some plugins, their software will complain, but all will be fine, however when updating to 2.6.0+, there is a dependency hell that requires a who load of other plugins to be updated, and things start breaking left and right :-(. I went down that road a few times and it caused havoc, and I had to revert things (I really want that 2.6.0). Having 2.5.1, however, let me bring all our masters back in business quickly and relatively safely.

**Comment by jetersen** [comment]
Honestly that's not a good reason for backporting, the dependencies which are updated should not cause dependency hell... if CloudBees is that far behind on updating plugins I am not sure what their managed masters are good for... 😅
2.6.0 was released on Nov 7, 2019 that's 5 months ago.

**Comment by mlasevich** [comment]
You are not entirely wrong, but there are other reasons for using their product that is not specific to versions of plugins... I do agree that  5 mos is way too long to be behind and expressed that to them :-)

**Comment by muppet3000** [comment]
Hi All, for what it's worth we've now hit this issue on our multiple Jenkins instances across our business (our central infra team upgraded to BB 7.0.1 over the weekend).
Have stumbled across this issue in the process. As we've been debugging with our infra team, we've come across this: https://jira.atlassian.com/browse/BSERV-12284?focusedCommentId=2389584&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2389584
Looks like it's in response to a comment where this thread is linked. 
Very keen to test an RC or release when it's available.

**Comment by muppet3000** [comment]
Hi again, can confirm that the following RC build: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc629.f242e60a14b4/ (link copied from above) solves the problem for us. 
We still see the "Lightweight error" at the beginning of the run, however it then continues without issue.

**Comment by tomk3003** [comment]
We got hit by the same problem after upgrade to Bitbucket Server 7.1.2.
I installed the latest RC version from [https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc632.56cea7d4b7e6/](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc632.56cea7d4b7e6/) but now the PR build fails on fetching the PR with the following error:

    ERROR: Error cloning remote repo 'origin'
    hudson.plugins.git.GitException: Command "git fetch --no-tags --progress -- https://idesuite.hlb.helaba.de/bitbucket/scm/MX/tool.build_deploy.git +refs/pull-requests/34/from:refs/remotes/origin/PR-34" returned status code 128:
    stdout: 
    stderr: fatal: Couldn't find remote ref refs/pull-requests/34/from
    
    	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
    	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
    	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
    	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
    	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
    	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1122)
    	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
    	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
    	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
    	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
    	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
    	at hudson.model.ResourceController.execute(ResourceController.java:97)
    	at hudson.model.Executor.run(Executor.java:428)
    ERROR: Error cloning remote repo 'origin'

Does this need a minimum git version on the jenkins agent? We have the default RHEL 7 Version 1.8.3.1.

**Comment by jetersen** [comment]
both Jenkins master and agent will need git to do heavy checkouts, even if the Jenkins master only needs the Jenkinsfile.

**Comment by tomk3003** [comment]
We have git, I was asking whether we need a version > 1.8.3.1. I was suspicious that the remote ref in the error message was incomplete (everything after the '/from' is missing).

**Comment by muppet3000** [comment]
> We got hit by the same problem after upgrade to Bitbucket Server 7.1.2.
> I installed the latest RC version from https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc632.56cea7d4b7e6/ but now the PR build fails on fetching the PR with the following error:
> 
> ```
> ERROR: Error cloning remote repo 'origin'
> hudson.plugins.git.GitException: Command "git fetch --no-tags --progress -- https://idesuite.hlb.helaba.de/bitbucket/scm/MX/tool.build_deploy.git +refs/pull-requests/34/from:refs/remotes/origin/PR-34" returned status code 128:
> stdout: 
> stderr: fatal: Couldn't find remote ref refs/pull-requests/34/from
> 
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
> 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1122)
> 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
> 	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
> 	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
> 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:428)
> ERROR: Error cloning remote repo 'origin'
> ```
> 
> Does this need a minimum git version on the jenkins agent? We have the default RHEL 7 Version 1.8.3.1.

From what I can tell there hasn't been any changes to the plugin that would require a change to the version of git you're using. All that has been changed is a call the the Bitbucket API.
Are you sure you've installed the RC plugin correctly (you can check it on the 'installed' tab in the plugins section of Jenkins)?
I only ask because the error you've quoted looks very similar to the one quoted in the first post above (after you read past the REST API failure)

**Comment by tomk3003** [comment]
Yes, the plugin seems to be installed correctly. I had to delete the PR including the commits and created them from scratch, then issued a new PR. Now the Jenkinsfile was not found by the Scan. After I opened the Diff tab of the PR (getting a Bitbucket error on the first try), the build was triggered. This seems to be another issue. I'll read up on it.

**Comment by muppet3000** [comment]
Ah yes, when our BB server was first upgraded we did see that we had to
delete and recreate some PRs, since upgrading to the RC build of the plugin
though we've had no issues.
(I support multiple Jenkins servers across our estate, all pointing at the
same BB server. Since installing the RC build the only problem we've had is
the one I mentioned above about the lightweight checkout failing).

**Comment by tomk3003** [comment]
After reading a lot, I have a question about the current status:

With the current RC the PRs are only detected after manually opening the PR in Bitbucket and then manually triggereing a pipeline scan? At least this is the status of our installation.

And this will perhaps be fixed with PR #302 ?

Please correct me if I'm wrong.

**Comment by muppet3000** [comment]
Before the upgrade, how were you triggering PR detection in Jenkins?
We use the "Post Webhooks" plugin in Bitbucket to hit this plugin in
Jenkins at the /scm-notify..... URL (sorry, can't remember the full URL and
I'm replying from my phone as not at work today).
Note that if you're now using the built-in Bitbucket "Webhooks" feature,
you need to change the URL slightly to include the URL of the Bitbucket
server when the request is sent.
This isn't something new or different in the plugin (it's documented quite
clearly already on the Jenkins plugin site for this plugin) it's just an
idea for something to look at in the configuration of your repo in
Bitbucket.

The Webhooks feature that's built into Bitbucket now has all sorts of
features for debugging the Webhooks as well as determining when they're
triggered.

This is all under the assumption you're using Webhooks to trigger the
builds (makes sense if you're using this plug-in).

**Comment by dcherniv** [comment]
@tomk3003 in jenkins settings https://jenkins/configure
make sure that 

"Webhook implementation to use" is set to "native". Plugin webhook no longer appears to work with PR.
Once you change that, re-scan the projects and you should see that jenkins set a webhook in BB in Webhooks (in project settings).

**Comment by muppet3000** [comment]
@dcherniv I'm sorry but I have to disagree with it not working with the "Plugin webhook" as it's working for us. HOWEVER, we've never used the "Manage hooks" feature in this plugin, we've always set the Webhooks manually in Bitbucket as we have a job to automate the creation of our Bitbucket repos with common settings.
I can definitely confirm though that we have PRs being triggered, using the "Post Webhooks" Bitbucket plugin, to this SCM plugin, without any problem.

**Comment by tomk3003** [comment]
We were using native Webhooks from the start. The webhooks are working. For merging PRs everything works fine. But the PRs are not recognized after creation. The scan says "Checking PR-..., Jenkinsfile not found". If I visit the PR in bitbucket and do a rescan, the PR is recognized and the pipeline runs. I have checked the webhook status in Bitbucket: the events have fired and have a successful status.

**Comment by muppet3000** [comment]
So what happens when the webhook fires for PR, does Jenkins just not do
anything? You have to manually scan it?
Because you shouldn't have to manually scan it at all if you're using
Webhooks.

**Comment by viceice** [comment]
We use jenkins with native webhoock mode and the plugin build from this pr. PR are visible and where build in jenkins. Only caveat it the heavy checkout.

**Comment by tomk3003** [comment]
Perhaps this only happens when the PR is done from a fork. In [this](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294#issuecomment-613294328) comment  in #294 the same behaviour is mentioned.

**Comment by wololock** [comment]
For those who installed RC version and still see the problem - make sure you install the correct one https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.7.1-rc629.f242e60a14b4/ We installed the newer RC version today and still see the problem. Installing exactly this one solved it for us - building pull requests on Jenkins work back again for us.

**Comment by muppet3000** [comment]
@wololock great spot, I would have just assumed that the latest RC was the same content as the one I posted a couple of days back.

@tomk3003 I'd recommend using the same version of the plugin mentioned by me and @wololock above and see if your issue resolves itself.

**Comment by tomk3003** [comment]
Thanks, I will do this first thing tomorrow morning and give an update.

**Comment by tomk3003** [comment]
Ok, tested the RC release @wololock mentioned. But the behaviour does not change. PRs from forks are not recognized. PRs in the same repo are working without problems. After opening the PR in Bitbucket the PRs from forks are recognized with a rescan.

**Comment by tomk3003** [comment]
But now the PR from forks cannot be built at all with the same error I posted in my first post. Even with a completly new PR. I will reinstall the latest RC and check again. I hope I can get the semi working state back.

**Comment by tomk3003** [comment]
Ok, back to the latest RC and I can use the PRs again with the manual workaroud. But now the "repo-local" PRs suffer from the same problem and have to be triggered manually. So it seems the last RC did fix part of the problem for the forked PRs but this affected the repo-local PRs as well.

**Comment by muppet3000** [comment]
Does the latest release imply that this ticket can now be closed?
The linked issue implies there may be something else that is now broken.
Can someone comment here on the new status?

**Comment by jetersen** [comment]
This is still not resolved.

**Comment by muppet3000** [comment]
@jetersen Thanks for the update.
Do we know if there's an RC build of the latest release e.g. 2.8.1 that has the PR code merged into it? Or should we be taking the previous RC still?

**Comment by mattiassluis** [comment]
I think PR https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294 fixes this at least to a decent level. I think it is almost done but needs some docs, perhaps @jetersen can reply to the last question on the PR. After that it can hopefully be merged and released? 🙏

**Comment by muppet3000** [comment]
Awesome.
It would be great to have an RC build rebased on top of the latest release so we can confirm they all work together. 
It will also stop our Jenkins instance from complaining that there are out-of-date plugins :P 
Happy to test as soon as there's another RC available.
Genuinely interested in how/when the RCs are built especially if there's a way of knowing what's in each of them.

**Comment by mattiassluis** [comment]
The latest RC includes the latest 2.8.0 release (hence the 2.8.1-rc naming). I think it holds that + the changes of a specific pull request (you can identify them on the commit hash in the name and related them to a commit of a specific PR)

**Comment by muppet3000** [comment]
Ah yes, that tracks with the previous build mentioned above with the "f242e6" branch.
Now it's just a case of getting a build that includes all of your latest changes. I assume it's something that the module owner is in control of.

**Comment by mattiassluis** [comment]
I think that will require an official release or at least for the PRs to be merged. I would also love to see that once the PRs to resolve Bitbucket 7 issues are finished

**Comment by jetersen** [comment]
I merged master into the PR, so you will have a the latest. Usually Jenkins will do a merge but better safe than sorry :)

**Comment by muppet3000** [comment]
@jetersen How does the build end up on the servers here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/  ?

Is that something you control, or is it the central Jenkins/cloudbees servers that control that?

**Comment by jetersen** [comment]
@muppet3000 like this:
https://github.com/jenkins-infra/pipeline-library/blob/148485040122e8d2f6faec30b54b119740515a57/vars/buildPlugin.groovy#L203-L205
https://github.com/jenkins-infra/pipeline-library/blob/148485040122e8d2f6faec30b54b119740515a57/vars/infra.groovy#L259-L279
https://github.com/jenkinsci/incrementals-tools

**Comment by muppet3000** [comment]
@jetersen Thanks for the info.

For anyone else that wants to test, the latest build is here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.8.1-rc646.71e4d09c0b37/

We'll update a couple of our instances and report back if anything is broken (otherwise assume it's fine).

**Comment by muppet3000** [comment]
Looks good, we still see the "Lightweight checkout failed" issue, but I assume that's to be expected.

**Comment by mattiassluis** [comment]
I think Bitbucket made it impossible to do a lightweight checkout for a the merged version of the pull request. That ref that was accessed through the API of Bitbucket no longer exists leaving two options:
1) Heavy weight checkout (doing the merge on Jenkins)
2) Switch to building the PR without the merge (which most of us find undesirable)
I don't think this feature will come back anytime soon but maybe a feature can be created to choose where the Jenkinsfile should be pulled from (separately from how the code should be build):
1 - From the target branch
2 - From the PR (without merge with the target branch)
3 - Merged (requires heavyweight checkout on Bitbucket Server 7+)

**Comment by muppet3000** [comment]
Cool.
I have no problem with a heavyweight build. The thought of not having the code merged in the build seems pointless!

**Comment by tomk3003** [comment]
I will be able to test this on sunday.

**Comment by muppet3000** [comment]
I spoke too soon. The latest merge or latest changes have reverted back to the previous cloning behaviour. e.g.:

`git fetch --no-tags --progress -- https://<BITBUCKET_REPO_URL>.git +refs/pull-requests/78/from:refs/remotes/origin/PR-78 # timeout=10`

however, the previous RC of the plugin switched to using the following:
`git fetch --no-tags --progress -- https://<BITBUCKET_REPO_URL>.git +refs/heads/<PR-SOURCE-BRANCH>:refs/remotes/origin/<PR-SOURCE-BRANCH># timeout=10`

The reason I thought it worked is because for some reason our Bitbucket instance is still creating the old style of ref but on it's own timescale and there's no guarantee that it will exist.
As such, when I tested the upgrade on a PR that already existed, it worked first time. Also, in some cases, if Bitbucket creates the ref quickly enough before the Jenkins instance actions the webhook it will also appear to work correctly.

Not sure how this has happened, potentially the merge in from master? Interested to see & test a fix when it's available.

For now, we're reverting back to the previous RC which is working fine.

**Comment by mattiassluis** [comment]
Did you make sure to check the checkbox 'callChanges' in the configuration? That should ensure the ref exists before cloning?

**Comment by muppet3000** [comment]
@mattiassluis No I didn't, I expected the plugin to work how it always has done. I'll test it with your suggestion now.
What is the correct behaviour out of the two examples I posted above then?
What is the scenario where you wouldn't want to "callChanges"? Surely you always want to ensure that the PR exists before you try to pull it?

**Comment by mattiassluis** [comment]
I think the scenario where you wouldn't want this is when you are running Bitbucket Server < 7.
I just installed the latest RC as well, we still see some strange cases where sometimes it works and other times it doesn't. Maybe the latest RC resolves that. 
It seems to work fine on new pull requests but when updating pull requests it is not really clear what happens. Of course we rebase a lot which suggests it also needs the fix I made to be included to handle the new incoming event as well.

**Comment by muppet3000** [comment]
Ok makes sense. Would be great if the plugin could intelligently decide whether to call it or not i.e. by looking at the REST API of bitbucket and finding out what version it was.
There are 2 options now in the configuration of the plugin: 
- Call Can Merge
- Call Changes api

The latter has a helpful message including "(since BitBucket Server v7)", but the first one doesn't say if it's specific to > BB v 7 or not.

I've ticked them both but I'm not sure if that's the correct thing to do.
It does appear to have fixed the problem though.

**Comment by joaoportela** [comment]
We're having the same issue. The PR #294 seems to fix it.

We got the build [2.8.1-rc648.98e3c549af77](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.8.1-rc648.98e3c549af77/) from jenkins-ci repo.

We enabled the "Call Changes API" option at https://SERVERADDRESS/configure like you guys said.
![image](https://user-images.githubusercontent.com/217176/81401295-eed5df80-9126-11ea-9c3e-f6546027a943.png)

Unfortunately, it still falls back to *heavyweight checkout* but at least the heavyweight checkout **is working**. 😄

**Comment by viceice** [comment]
lightweight checkout is no longer possible with bitbucket server v7 and merge build strategy, because bitbucket no longer computes a merge commit.

**Comment by joaoportela** [comment]
Just another update from my side.

Looking at the build logs and comparing it with PR #294 changes it didn't seem to be using the "Call changes API" code path.

So I unchecked that option and ran the builds again and it still works... 🤷‍♂️

I guess the issue for me was something that hadn't made it into stable release yet.

More details if you guys need it:
- Jenkins version 2.222.3
- Bitbucket version 7.1.1

**Comment by mattiassluis** [comment]
@joaoportela actually that makes perfect sense if you didn't push any new changes in between. The "Call changes API" only needs to be called once to ensure the refs are created on Bitbucket. This is also what happens if you view the diff in the Bitbucket UI. Once the refs are created the plugin can do its thing (with the heavyweight checkout).
What the "Call changes API" does is ensure that Bitbucket for sure created the refs (because with Bitbucket 7 they are only created on demand).

**Comment by mattiassluis** [comment]
With regards to my earlier comment: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/287#issuecomment-625283903 This seems to be some mistake with the webhooks on our end. The latest releases have worked good for us (but since we need to roll this out to many Jenkins servers we are hoping on an official release soon)

**Comment by tomk3003** [comment]
I just tested with [2.8.1-rc648.98e3c549af77](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.8.1-rc648.98e3c549af77/) with "Call Changes api" activated and "Can Call Merge" deactivated against Bitbucket Server 7.1.2 and can confirm that PRs from within a repo as well as PRs from forks are triggered successfully.. The only thing that is still missing, is triggering a build when a PR gets pushed into. But I think for that, handling of the new webhook "Source branch updated" (#308) is needed.

**Comment by JeroennC** [comment]
Another github user @Cyanoth created an alternative solution to this issue, creating a bitbucket plugin that executes the `diff` call whenever a PR is created / updated: https://github.com/Cyanoth/Bitbucket-EagerPR-Updates 

We've just installed this to our bitbucket server, and it works well. I'm not sure if it guarantees the `refs/pull-requests/<x>/from` ref is updated before the Jenkins job is triggered though.

I also like how this solution works regardless of the CI used. Would be best if this plugin still gets #294 though IMO

**Comment by mike-sol** [comment]
Still seeing this issue on the first build of a multibranch pipeline with 2.8.1-rc648.98e3c549af77  installed. Subsequent, manually triggered builds seem to work.

`Branch event
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/REPONAME/repos/REPONAME/browse/rpm/pipelines/pull-request/Jenkinsfile?at=pull-requests%2F2636%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:855)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1150)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Checking out git https://git.REDACTED.local/scm/REPONAME/REPONAME.git https://git.REDACTED.local/scm/REPONAME/REPONAME.git into /var/lib/jenkins/workspace/SSW_REPONAME-pr-build_PR-2636@script to read rpm/pipelines/pull-request/Jenkinsfile
using credential CREDENTIAL-NAME
using credential CREDENTIAL-NAME
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://git.REDACTED.local/scm/REPONAME/REPONAME.git
 > git init /var/lib/jenkins/workspace/SSW_REPONAME-pr-build_PR-2636@script # timeout=10
Fetching upstream changes from https://git.REDACTED.local/scm/REPONAME/REPONAME.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Read-only personal access token for stash.jenkins BitBucket user
 > git fetch --no-tags --force --progress -- https://git.REDACTED.local/scm/REPONAME/REPONAME.git +refs/pull-requests/2636/from:refs/remotes/origin/PR-2636 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress -- https://git.REDACTED.local/scm/REPONAME/REPONAME.git +refs/pull-requests/2636/from:refs/remotes/origin/PR-2636" returned status code 128:
stdout: 
stderr: fatal: couldn't find remote ref refs/pull-requests/2636/from

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1122)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
ERROR: Error cloning remote repo 'origin'
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE`

**Comment by spacehorst** [comment]
The first build for a new PR is also automatically triggered and successfully built on the before mentioned configuration of our systems.

**Comment by mike-sol** [comment]
@spacehorst You mention "Bitbucket Server 7.1.0 setting "Call Changes API" true and "Can Call Merge" false" - where does one configure those? Were they non-default settings?

**Comment by muppet3000** [comment]
There's a discussion on this a few posts up from myself.
Those options are in the settings for the plugin in Jenkins i.e. where you
configure the address etc. for your Bitbucket server.
They're not on by default because the developer doesn't want to assume that
everyone is using the latest version of Bitbucket, if you're running an
older version those options will cause the plugin to fail.
I believe I made the suggestion that the plugin could query the Bitbucket
REST API to find out what version of Bitbucket was being used and then
apply the correct setting accordingly.
I'm not a Java Dev so I don't really know how hard that is to actually
implement.

**Comment by mike-sol** [comment]
Thanks @muppet3000, I have enabled that option and will report back when my devs have tested things out.

**Comment by mike-sol** [comment]
Looks like we're good over here. Here's the top of the build output from a now-working PR. 

It would be nice if it didn't throw the exception, and instead have some way to detect this case and not litter build output with unnecessary errors.

```Branch event
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/REPO/repos/REPO/browse/rpm/pipelines/pull-request/Jenkinsfile?at=pull-requests%2F2647%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:855)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1150)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Checking out git https://git.COMPANY.local/scm/REPO/REPO.git https://git.COMPANY.local/scm/REPO/REPO.git into /var/lib/jenkins/workspace/SSW_REPO-pr-build_PR-2647@script to read rpm/pipelines/pull-request/Jenkinsfile
using credential CRED
using credential CRED
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://git.COMPANY.local/scm/REPO/REPO.git
 > git init /var/lib/jenkins/workspace/SSW_REPO-pr-build_PR-2647@script # timeout=10
Fetching upstream changes from https://git.COMPANY.local/scm/REPO/REPO.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Read-only personal access token for stash.jenkins BitBucket user
 > git fetch --no-tags --force --progress -- https://git.COMPANY.local/scm/REPO/REPO.git +refs/pull-requests/2647/from:refs/remotes/origin/PR-2647 # timeout=10
 > git config remote.origin.url https://git.COMPANY.local/scm/REPO/REPO.git # timeout=10
 > git config --add remote.origin.fetch +refs/pull-requests/2647/from:refs/remotes/origin/PR-2647 # timeout=10
 > git config remote.origin.url https://git.COMPANY.local/scm/REPO/REPO.git # timeout=10
Fetching without tags
Fetching upstream changes from https://git.COMPANY.local/scm/REPO/REPO.git
using GIT_ASKPASS to set credentials Read-only personal access token for stash.jenkins BitBucket user
 > git fetch --no-tags --force --progress -- https://git.COMPANY.local/scm/REPO/REPO.git +refs/pull-requests/2647/from:refs/remotes/origin/PR-2647 # timeout=10
 > git config remote.upstream.url https://git.COMPANY.local/scm/REPO/REPO.git # timeout=10
Fetching without tags
Fetching upstream changes from https://git.COMPANY.local/scm/REPO/REPO.git
using GIT_ASKPASS to set credentials Read-only personal access token for stash.jenkins BitBucket user
 > git fetch --no-tags --force --progress -- https://git.COMPANY.local/scm/REPO/REPO.git +refs/heads/master:refs/remotes/upstream/master # timeout=10
Merging remotes/upstream/master commit 96ca0c51ba0d19112daf521fa3e97c2603f7345e into PR head commit fc69bfd35092dd27d31e7c1d1e7774296038c625
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fc69bfd35092dd27d31e7c1d1e7774296038c625 # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
using GIT_ASKPASS to set credentials Read-only personal access token for stash.jenkins BitBucket user
 > git merge 96ca0c51ba0d19112daf521fa3e97c2603f7345e # timeout=10
 > git rev-parse HEAD^{commit} # timeout=10
Merge succeeded, producing fc69bfd35092dd27d31e7c1d1e7774296038c625
Checking out Revision fc69bfd35092dd27d31e7c1d1e7774296038c625 (PR-2647)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fc69bfd35092dd27d31e7c1d1e7774296038c625 # timeout=10
Commit message: "Revert "Reverting changes to demo.py""
First time build. Skipping changelog.
[Bitbucket] Notifying pull request build result
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline (show)
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
Finished: SUCCESS

**Comment by jglick** [comment]
> It would be nice if it didn't throw the exception, and instead have some way to detect this case and not litter build output with unnecessary errors.

That would have to be in https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/a18e9d41dca08652d2bb2ce71fbf113e9ae5fb5a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java#L100

Be sure to test not just an empty `Jenkinsfile` but one including

```groovy
node {
  checkout scm
}
```

**Comment by muppet3000** [comment]
I've just had a new issue brought to my attention on this and I don't know if it's as a result of the changes to the plugin or something else. Would be grateful if others could confirm.
We have our Jenkins configured in "Exclude branches that are also filed as PRs", however, quite often someone will make some changes to a feature and push them, then immediately create a PR.
This results in a running "feature" branch job, and then another running "PR" job following shortly behind. In bitbucket however, this shows as just a single running job - whatever one was triggered last (in this case the PR), but I'm 100% certain that it used to show as 2 jobs - one for the feature branch and another for the PR branch.

What happens is that the feature job finishes whilst the PR is still running and then updates the job status on the Bitbucket PR/commit to show that the feature branch has passed. This allows a PR to then be merged whilst a job (the PR job) is still running, breaking the whole point of having a PR build.

Has anyone else seen this behaviour? I'll do more investigation tomorrow to determine whether or not this is related to this plugin, or another plugin. I'll attempt to roll back the plugin we have installed on one of our instances to a "pre dev" build of this one and see if the behaviour persists or goes away, if it goes away then the issue is in this "fix". 

Can anyone else out there confirm whether they're seeing the same issue with this dev build of the plugin? We've just upgraded all of our Jenkins instances to the latest LTS and latest plugins, so there have been lots of changes that I need to rule out.

**Comment by viceice** [comment]
@muppet3000 I've seen this too, this has nothing todo with this issue. So please file a new issue for that

**Comment by muppet3000** [comment]
I understand that the symptoms are nothing to do with this issue. My
question is more whether or not someone has seen this issue when NOT using
this dev build of the plugin. In other words, have the changes implemented
to fix this issue accidentally caused a different issue?

**Comment by viceice** [comment]
@muppet3000 sorry, I've seen it before I switch to the dev build. I have some jobs which requires 15 and more minutes to succeed, so if I push a branch and open a PR shortly after it, I can see your behavior on all releases since ~1 year

**Comment by muppet3000** [comment]
That's so weird, I'm certain that it used to post multiple build statuses
to Bitbucket one for each branch type in Jenkins. I'll put some effort into
debugging/analysing it properly tomorrow and log a new issue for people to
add their comments to.

**Comment by muppet3000** [comment]
@viceice I've just created this new issue to address the separate problem we discussed yesterday: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/324
Would appreciate your +1/backing/comments on it to help bump it up the priority.

**Comment by mlasevich** [comment]
Just run into an issue with falling back to heavyweight checkout. When faced with a repo that has LSF enabled,  it tries to do LFS, which is not available on master. My two questions are - have the issue of falling back to heavyweight been resolved here and if not, is there a way to disable LFS during heavyweight checkout for purposes of this plugin while still having it enabled for actual checkout on the remote nodes?

**Comment by jetersen** [comment]
regarding LFS checkout, I toyed with the idea of either an extension plugin or a contribution to the git plugin to add a scm filter for ignoring LFS checkout on master. Never got anywhere but should be simple to write a filter.

The issue of heavy checkout has not been resolved.

**Comment by jetersen** [comment]
Added some solution for LFS checkout on master.

**Comment by mlasevich** [comment]
Thanks. For now I removed the LFS from my job config and added it manually in checkout step in Jenkinsfile(hurray for global libs) - but it would be much cleaner using the env variable being that master does not even have LFS installed, so it will not work in any case.

**Comment by jetersen** [comment]
Ya that's where the plugin would be useful when LFS is not installed on master.
